import { z } from 'zod';
import { IsoDateTime, LocalDate, Uuid } from './common';

export const MilestoneSchema = z.object({
  id: Uuid,
  title: z.string(),
  date: LocalDate,
  note: z.string().nullable(),
  icon: z.string().nullable(),
  isAutoGenerated: z.boolean(),
  createdAt: IsoDateTime,
});
export type Milestone = z.infer<typeof MilestoneSchema>;

export const CreateMilestoneSchema = z.object({
  title: z.string().min(1, 'judul wajib diisi').max(120),
  date: LocalDate,
  note: z.string().max(1000).nullable().default(null),
  icon: z.string().max(8).nullable().default(null),
});
export const UpdateMilestoneSchema = CreateMilestoneSchema.partial();

export const MILESTONES_PATHS = {
  list: '/milestones',
  create: '/milestones',
  byId: (id: string) => `/milestones/${id}`,
} as const;
