import type {
  CoupleRole, EventCategory, JournalVisibility, LetterUnlockType, MemoryType,
  MoodLevel, NotificationCategory, QuestionCategory, RelationshipDateLabel,
  DatePlanStatus, DatePlanSource, GameKey, PlanStep, PlannerInput,
} from '@couple/contracts';

/** Bentuk baris "database" mock. Sengaja mirip Prisma model di Fase 2. */
export interface UserRow {
  id: string;
  email: string;
  displayName: string;
  avatarPath: string | null;
  timezone: string;
  createdAt: string;
}

export interface CoupleRow {
  id: string;
  name: string | null;
  photoPath: string | null;
  relationshipDate: string;
  relationshipDateLabel: RelationshipDateLabel;
  theme: string;
  timezone: string;
  streakCount: number;
  streakLongest: number;
  streakLastActiveOn: string | null;
  createdAt: string;
}

export interface MemberRow {
  coupleId: string;
  userId: string;
  role: CoupleRole;
  joinedAt: string;
}

export interface InviteRow {
  id: string;
  coupleId: string;
  code: string;
  createdById: string;
  expiresAt: string;
  usedAt: string | null;
  usedById: string | null;
  revokedAt: string | null;
}

export interface QuestionRow {
  id: string;
  category: QuestionCategory;
  text: string;
}

export interface AnswerRow {
  authorId: string;
  body: string;
  createdAt: string;
}

export interface DailyRow {
  id: string;
  coupleId: string;
  questionId: string;
  localDate: string;
  answers: AnswerRow[];
}

export interface MediaRow {
  id: string;
  storagePath: string;
  width: number | null;
  height: number | null;
}

export interface MemoryRow {
  id: string;
  coupleId: string;
  type: MemoryType;
  caption: string | null;
  happenedAt: string;
  location: string | null;
  isFavorite: boolean;
  createdById: string;
  createdAt: string;
  media: MediaRow[];
}

export interface JournalRow {
  id: string;
  coupleId: string;
  authorId: string;
  title: string | null;
  body: string;
  visibility: JournalVisibility;
  createdAt: string;
  updatedAt: string;
}

export interface MoodRow {
  id: string;
  coupleId: string;
  userId: string;
  level: MoodLevel;
  note: string | null;
  localDate: string;
  createdAt: string;
}

export interface EventRow {
  id: string;
  coupleId: string;
  title: string;
  category: EventCategory;
  date: string;
  time: string | null;
  location: string | null;
  budgetIdr: number | null;
  notes: string | null;
  reminderMinutes: number | null;
  isAllDay: boolean;
  createdById: string;
  createdAt: string;
}

export interface WishlistRow {
  id: string;
  coupleId: string;
  title: string;
  note: string | null;
  estimatedIdr: number | null;
  isDone: boolean;
  addedById: string;
  doneAt: string | null;
  createdAt: string;
}

export interface DatePlanRow {
  id: string;
  coupleId: string;
  title: string;
  status: DatePlanStatus;
  source: DatePlanSource;
  input: PlannerInput;
  steps: PlanStep[];
  totalIdr: number;
  createdAt: string;
}

export interface MilestoneRow {
  id: string;
  coupleId: string;
  title: string;
  date: string;
  note: string | null;
  icon: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface LetterRow {
  id: string;
  coupleId: string;
  authorId: string;
  title: string;
  body: string;
  unlockType: LetterUnlockType;
  unlockOn: string;
  openedAt: string | null;
  createdAt: string;
}

export interface GameSessionRow {
  id: string;
  coupleId: string;
  key: GameKey;
  roundIds: string[];
  picks: Record<string, Record<string, string>>;
  finishedBy: string[];
  score: number | null;
  finishedAt: string | null;
  createdAt: string;
}

export interface NotificationRow {
  id: string;
  coupleId: string;
  userId: string;
  category: NotificationCategory;
  title: string;
  body: string;
  link: string | null;
  readAt: string | null;
  createdAt: string;
}

export interface PrefRow {
  userId: string;
  category: NotificationCategory;
  push: boolean;
  email: boolean;
}
