import { db } from '../../mocks/db';
import { delay, fail } from '../../mocks/simulate';
import { currentCouple } from '../../utils/currentUser';

export default defineEventHandler(async (event) => {
  await delay(200);
  const { couple } = currentCouple(event);
  const id = getRouterParam(event, 'id');
  const row = db.milestones.find(m => m.id === id && m.coupleId === couple.id);
  if (!row) fail(404, 'NOT_FOUND', 'Milestone tidak ditemukan.');
  if (row.isAutoGenerated) fail(409, 'MILESTONE_AUTO', 'Milestone otomatis tidak bisa dihapus.');
  db.milestones = db.milestones.filter(m => m.id !== id);
  return { ok: true };
});
