import { CreateMilestoneSchema } from '@couple/contracts';
import { db, uid } from '../../mocks/db';
import { toMilestone } from '../../mocks/map';
import { delay, maybeFail } from '../../mocks/simulate';
import { currentCouple, failRate } from '../../utils/currentUser';
import { parseBody } from '../../utils/validate';
import { nowIso } from '../../utils/clock';

export default defineEventHandler(async (event) => {
  await delay();
  maybeFail(failRate(event));
  const { couple } = currentCouple(event);
  const body = parseBody(CreateMilestoneSchema, await readBody(event));

  const row = {
    id: uid(),
    coupleId: couple.id,
    title: body.title,
    date: body.date,
    note: body.note,
    icon: body.icon,
    isAutoGenerated: false,
    createdAt: nowIso(),
  };
  db.milestones.push(row);
  setResponseStatus(event, 201);
  return toMilestone(row);
});
