<script setup lang="ts">
definePageMeta({ middleware: 'couple-required' });
useHead({ title: 'Milestone' });

const { items, byYear, status, error, refresh, remove } = useMilestones();
const coupleStore = useCoupleStore();
const ui = useUiStore();

const today = computed(() => localDate(coupleStore.timezone));

/** "Berikutnya" dihitung dari utils/date, bukan aritmetika Date mentah. */
const upcoming = computed(() => {
  const couple = coupleStore.couple;
  if (!couple) return [];

  const days = couple.daysTogether;
  const nextRound = (Math.floor(days / 100) + 1) * 100;
  const roundDate = addDays(couple.relationshipDate, nextRound);

  const years = Math.floor(days / 365) + 1;
  const anniversary = addDays(couple.relationshipDate, years * 365);

  return [
    { title: `${formatNumber(nextRound)} hari`, date: roundDate, inDays: diffDays(today.value, roundDate) },
    { title: `Anniversary ke-${years}`, date: anniversary, inDays: diffDays(today.value, anniversary) },
  ].sort((a, b) => a.inDays - b.inDays);
});

const removeTarget = ref<string | null>(null);
const removing = ref(false);

async function onRemove() {
  if (!removeTarget.value) return;
  removing.value = true;
  try {
    await remove(removeTarget.value);
    ui.toast('Milestone dihapus', 'success');
  } catch (e) {
    ui.toast(apiErrorMessage(e), 'danger');
  } finally {
    removing.value = false;
    removeTarget.value = null;
  }
}
</script>

<template>
  <div>
    <NavAppHeader title="Milestone" />

    <div class="px-4 py-4">
      <section v-if="upcoming.length" class="mb-7">
        <h2 class="mb-2.5 section-label">Berikutnya</h2>
        <div class="grid grid-cols-2 gap-2">
          <div v-for="u in upcoming" :key="u.title" class="solid-card p-3.5">
            <p class="text-[15px] font-semibold">{{ u.title }}</p>
            <p class="mt-1 text-[13px] text-[var(--color-ink-soft)]">{{ formatDate(u.date) }}</p>
            <p class="text-display mt-1.5 text-lg text-[var(--color-primary)]">
              {{ u.inDays > 0 ? `${u.inDays} hari lagi` : 'hari ini' }}
            </p>
          </div>
        </div>
      </section>

      <BaseSkeleton v-if="status === 'pending'" variant="card" :count="4" />
      <BaseErrorState v-else-if="error" :error="error" title="Milestone gagal dimuat" @retry="refresh()" />

      <BaseEmptyState
        v-else-if="!items.length"
        icon="star" title="Belum ada milestone"
        description="Tandai momen yang ingin kalian ingat tanggalnya."
        action-label="Tambah milestone" action-to="/milestones/new"
      />

      <div v-else class="flex flex-col gap-7">
        <section v-for="group in byYear" :key="group.year">
          <header class="sticky top-14 z-10 -mx-1 mb-2.5 bg-[var(--color-bg)] px-1 py-1.5">
            <h2 class="text-display text-lg">{{ group.year }}</h2>
          </header>

          <div class="flex flex-col gap-2">
            <div v-for="m in group.items" :key="m.id" class="solid-card flex items-start gap-3 p-4">
              <span class="grid size-10 shrink-0 place-items-center rounded-[var(--radius-field)] bg-[var(--color-primary-soft)] text-lg">
                {{ m.icon ?? '⭐' }}
              </span>
              <div class="min-w-0 flex-1">
                <p class="text-[15px] font-medium">{{ m.title }}</p>
                <p class="mt-0.5 text-[13px] text-[var(--color-ink-soft)]">{{ formatDate(m.date) }}</p>
                <p v-if="m.note" class="mt-1.5 text-[13px] text-[var(--color-ink-soft)]">{{ m.note }}</p>
                <BaseChip v-if="m.isAutoGenerated" class="mt-2" size="sm">Otomatis</BaseChip>
              </div>
              <button
                v-if="!m.isAutoGenerated" type="button" aria-label="Hapus milestone"
                class="del tap-target rounded-full p-1.5 text-[var(--color-ink-soft)]"
                @click="removeTarget = m.id"
              ><BaseIcon name="trash" :size="16" /></button>
            </div>
          </div>
        </section>
      </div>
    </div>

    <NuxtLink
      to="/milestones/new"
      class="pressable fixed right-4 bottom-24 z-30 grid size-14 place-items-center rounded-full
             bg-[var(--color-primary)] text-[var(--color-primary-ink)] shadow-[var(--shadow-card)] md:bottom-8"
      aria-label="Tambah milestone"
    ><BaseIcon name="plus" :size="24" /></NuxtLink>

    <BaseDialog
      :open="removeTarget !== null"
      title="Hapus milestone ini?" description="Tanggalnya tidak lagi muncul di linimasa."
      confirm-label="Hapus" tone="danger" :loading="removing"
      @update:open="(v: boolean) => { if (!v) removeTarget = null; }"
      @confirm="onRemove"
    />
  </div>
</template>

<style scoped>
.del { transition: color var(--dur-pop) var(--ease-out), transform var(--dur-press) var(--ease-out); }
.del:active { transform: scale(0.97); }
</style>
